spring:
  http:
    encoding:
      charset: UTF-8
      force: true
aws:
  region: il-central-1
  bucket:
    name: blood-bucket-donation
medications:
  file:
    path: src/main/resources/medications.json
logging:
  level:
    root: INFO